version: '3'
services:
    web:
        image: nginx:1.25.2-alpine3.18
        ports:
            - "8888:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./app:/app
        depends_on:
            - php
        restart: always
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app:user
        depends_on:
            - mysql
        restart: always
    mysql:
        image: mariadb:11.1.2-jammy
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: ''
            MYSQL_DATABASE: 'db'
        volumes:
            - slimApi:/var/lib/mysql
        ports:
            - "3325:3306"
        restart: always
volumes:
   slimApi: {}
        

